version: '2'

services:

  ezvis:
    container_name: ezvis
    image: inistcnrs/ezvis:6.8.7
    links:
      - ezvis_db
    # volumes:
    #   - ${EZVIS_DATA_DIR}:/app/data
    #   - ${EZVIS_DATA_CONF}:/app/data.json
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      NODE_ENV: "production"
      MONGO_HOST_PORT: "ezvis_db:27017"
      MONGO_DATABASE: "castor"
    ports:
      - 3000:3000
    restart: always

  ezvis_db:
    container_name: ezvis_db
    image: mongo:3.0.7
    command: --smallfiles